(() => {
  const GUARDIAN_API='https://guardian-api.william-xia-cn.workers.dev';
  const RUNTIME_API='https://timeonchrome-app-runtime-api.william-xia-cn.workers.dev';
  const mock=new URLSearchParams(location.search).has('mock');
  const state={period:'day',offset:0,token:null,childId:null,devices:[],timer:null};
  const $=(s)=>document.querySelector(s);
  const read=(k)=>{try{return JSON.parse(localStorage.getItem(`toc_${k}`));}catch{return null;}};
  const write=(k,v)=>localStorage.setItem(`toc_${k}`,JSON.stringify(v));
  const escape=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const duration=(ms)=>ms<60000?'少于 1 分钟':`${Math.floor(ms/3600000)?`${Math.floor(ms/3600000)} 小时 `:''}${Math.round(ms%3600000/60000)} 分钟`;
  const time=(ms)=>ms?new Date(ms).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'尚未同步';
  async function refreshSession(){const s=read('session');if(!s?.refreshToken)return false;const r=await fetch(`${GUARDIAN_API}/auth/refresh`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken:s.refreshToken})});if(!r.ok)return false;const p=await r.json();write('session',{...s,token:p.token,refreshToken:p.refreshToken||s.refreshToken});return true;}
  async function guardian(path){let s=read('session');if(!s?.token)throw new Error('请先登录家长控制台');let r=await fetch(`${GUARDIAN_API}${path}`,{method:'POST',headers:{Authorization:`Bearer ${s.token}`}});if(r.status===401&&await refreshSession()){s=read('session');r=await fetch(`${GUARDIAN_API}${path}`,{method:'POST',headers:{Authorization:`Bearer ${s.token}`}});}const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||'登录状态已过期');return p;}
  async function issue(){state.childId=read('currentProfileId');if(!state.childId)throw new Error('请先在家长控制台选择孩子');const p=await guardian(`/profiles/${encodeURIComponent(state.childId)}/app-runtime/token`);state.token=p.token;const part=p.token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/');const claims=JSON.parse(atob(part+'='.repeat((4-part.length%4)%4)));$('#child-name').textContent=claims.child_name||'当前孩子';}
  async function moduleToken(renew=false){if(renew)state.token=null;if(!state.token)await issue();return state.token;}
  async function runtime(path,options={}){return AppRuntimeNetwork.requestJson({url:`${RUNTIME_API}${path}`,options,getToken:moduleToken});}
  function range(){const now=new Date();const sh=new Date(now.toLocaleString('en-US',{timeZone:'Asia/Shanghai'}));if(state.period==='day'){sh.setHours(0,0,0,0);sh.setDate(sh.getDate()+state.offset);return{from:sh.getTime()-28800000,to:sh.getTime()-28800000+86400000,label:sh.toLocaleDateString('zh-CN')}}const day=(sh.getDay()+6)%7;sh.setHours(0,0,0,0);sh.setDate(sh.getDate()-day+state.offset*7);return{from:sh.getTime()-28800000,to:sh.getTime()-28800000+604800000,label:`${sh.toLocaleDateString('zh-CN')} 起一周`};}
  function mockData(){return{devices:[{id:'dev-a',displayName:'书房电脑',status:'online',agentVersion:'1.0.1',windowsVersion:'Windows 11',architecture:'x64',lastSeenAtMs:Date.now()-120000,lastSyncAtMs:Date.now()-180000},{id:'dev-b',displayName:'笔记本',status:'recentlyOnline',agentVersion:'1.0.1',windowsVersion:'Windows 11',architecture:'x64',lastSeenAtMs:Date.now()-7200000}],usage:{totalDurationMs:9720000,lastSyncAtMs:Date.now()-180000,buckets:Array.from({length:24},(_,i)=>({startAtMs:i,durationMs:[0,0,0,0,0,0,0,0,900000,1800000,1200000,600000,300000,1500000,2100000,720000,0,600000,0,0,0,0,0,0][i]})),applications:[{runtimeIdentity:'a',displayName:'Visual Studio Code',durationMs:4320000},{runtimeIdentity:'b',displayName:'Microsoft Edge',durationMs:2880000},{runtimeIdentity:'c',displayName:'微信',durationMs:1620000},{runtimeIdentity:'d',displayName:'文件资源管理器',durationMs:900000}]}};}
  function renderDevices(){const box=$('#devices');box.innerHTML=state.devices.length?state.devices.map(d=>`<article class="device-card"><div><strong>${escape(d.displayName||'Windows 电脑')}</strong><p>${escape(d.windowsVersion||'等待首次连接')} · ${escape(d.architecture||'x64')} · Agent ${escape(d.agentVersion||'—')}</p><p>最近在线 ${time(d.lastSeenAtMs)}</p></div><span class="badge ${escape(d.status)}">${({online:'在线',recentlyOnline:'最近在线',offline:'离线',pending:'待安装',revoked:'已吊销'})[d.status]||d.status}</span><div class="actions">${d.status!=='revoked'&&d.status!=='pending'?`<button data-replace="${escape(d.id)}">重新配对</button><button class="danger" data-revoke="${escape(d.id)}">吊销</button>`:''}</div></article>`).join(''):'尚未添加 Runtime 设备';const select=$('#device-filter');const current=select.value;select.innerHTML='<option value="">全部设备</option>'+state.devices.filter(d=>!['pending','revoked'].includes(d.status)).map(d=>`<option value="${escape(d.id)}">${escape(d.displayName)}</option>`).join('');select.value=current;}
  function renderUsage(u){$('#total-time').textContent=duration(u.totalDurationMs||0);$('#last-sync').textContent=time(u.lastSyncAtMs);const max=Math.max(1,...u.buckets.map(b=>b.durationMs));$('#usage-chart').innerHTML=u.buckets.map((b,i)=>`<div class="bar" title="${duration(b.durationMs)}" style="height:${Math.max(2,b.durationMs/max*100)}%"><span>${state.period==='day'?`${i}时`:new Date(b.startAtMs).toLocaleDateString('zh-CN',{weekday:'short',timeZone:'Asia/Shanghai'})}</span></div>`).join('');$('#app-ranking').className='list';$('#app-ranking').innerHTML=u.applications.length?u.applications.map((a,i)=>`<div class="app-row"><span class="app-icon">${i+1}</span><strong>${escape(a.displayName||'未知应用')}</strong><time>${duration(a.durationMs)}</time></div>`).join(''):'暂无使用记录';}
  async function load({freshToken=false}={}){try{if(freshToken)state.token=null;$('#status-strip').hidden=true;const r=range();$('#range-label').textContent=r.label;$('#chart-caption').textContent=`北京时间，${state.period==='day'?'按小时':'按每日'}`;if(mock){const d=mockData();state.devices=d.devices;renderDevices();renderUsage(d.usage);$('#child-name').textContent='小明（演示）';return;}const devices=await runtime('/v1/module/devices');state.devices=devices.devices;renderDevices();const filter=$('#device-filter').value;const usage=await runtime(`/v1/module/usage?fromMs=${r.from}&toMs=${r.to}${filter?`&deviceId=${encodeURIComponent(filter)}`:''}`);renderUsage(usage);}catch(e){$('#status-strip').hidden=false;$('#status-strip').textContent=AppRuntimeNetwork.friendlyError(e).message;}}
  async function pair(deviceId){if(mock){showPair('ABCD-EFGH-JKLM',Date.now()+600000);return;}const path=deviceId?`/v1/module/devices/${encodeURIComponent(deviceId)}/replace-pairing`:'/v1/module/pairing-codes';const p=await runtime(path,{method:'POST',body:'{}'});showPair(p.code,p.expiresAtMs);}
  function showPair(code,expires){$('#pair-code').textContent=code;$('#pair-dialog').showModal();clearInterval(state.timer);const tick=()=>{const sec=Math.max(0,Math.ceil((expires-Date.now())/1000));$('#pair-countdown').textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')} 后过期`;};tick();state.timer=setInterval(tick,1000);runtime('/v1/releases/windows/x64/latest').then(r=>{$('#download-installer').href=`${RUNTIME_API}/v1/releases/windows/x64/${encodeURIComponent(r.version)}/installer`;}).catch(()=>{$('#download-installer').removeAttribute('href');$('#download-installer').textContent='安装器准备中';});}
  document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.id==='add-device')await pair();if(b.dataset.replace)await pair(b.dataset.replace);if(b.dataset.revoke&&!mock){await runtime(`/v1/module/devices/${encodeURIComponent(b.dataset.revoke)}/revoke`,{method:'POST',body:'{}'});await load();}if(b.id==='copy-code')await navigator.clipboard.writeText($('#pair-code').textContent);if(b.dataset.period){state.period=b.dataset.period;state.offset=0;document.querySelectorAll('[data-period]').forEach(x=>x.classList.toggle('active',x===b));await load();}if(b.id==='previous'){state.offset--;await load();}if(b.id==='today'){state.offset=0;await load();}if(b.id==='refresh')await load({freshToken:true});}catch(err){$('#status-strip').hidden=false;$('#status-strip').textContent=AppRuntimeNetwork.friendlyError(err).message;}});$('#device-filter').addEventListener('change',()=>load());load();
})();
