(() => {
  const GUARDIAN_API='https://guardian-api.william-xia-cn.workers.dev';
  const RUNTIME_API='https://timeonchrome-app-runtime-api.william-xia-cn.workers.dev';
  const mock=new URLSearchParams(location.search).has('mock');
  const state={period:'day',offset:0,token:null,childId:null,children:[],machines:[],users:new Map(),timer:null};
  const $=(s)=>document.querySelector(s);
  const read=(k)=>{try{return JSON.parse(localStorage.getItem(`toc_${k}`));}catch{return null;}};
  const write=(k,v)=>localStorage.setItem(`toc_${k}`,JSON.stringify(v));
  const escape=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const duration=(ms)=>ms<60000?'少于 1 分钟':`${Math.floor(ms/3600000)?`${Math.floor(ms/3600000)} 小时 `:''}${Math.round(ms%3600000/60000)} 分钟`;
  const time=(ms)=>ms?new Date(ms).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'尚未同步';
  const child=(id)=>state.children.find(item=>item.id===id);
  const childKey=(id)=>String(state.children.findIndex(item=>item.id===id));
  const childFromKey=(key)=>state.children[Number(key)]||null;

  async function refreshSession(){const s=read('session');if(!s?.refreshToken)return false;const r=await fetch(`${GUARDIAN_API}/auth/refresh`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken:s.refreshToken})});if(!r.ok)return false;const p=await r.json();write('session',{...s,token:p.token,refreshToken:p.refreshToken||s.refreshToken});return true;}
  async function guardian(path){let s=read('session');if(!s?.token)throw new Error('请先登录家长控制台');let r=await fetch(`${GUARDIAN_API}${path}`,{method:'POST',headers:{Authorization:`Bearer ${s.token}`}});if(r.status===401&&await refreshSession()){s=read('session');r=await fetch(`${GUARDIAN_API}${path}`,{method:'POST',headers:{Authorization:`Bearer ${s.token}`}});}const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||'登录状态已过期');return p;}
  function claims(token){const part=token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/');return JSON.parse(atob(part+'='.repeat((4-part.length%4)%4)));}
  async function issue(){const p=await guardian('/app-runtime/account-token');state.token=p.token;const c=claims(p.token);state.children=Array.isArray(c.children)?c.children:[];state.childId=read('currentProfileId');const selected=child(state.childId)||state.children[0];if(!selected)throw new Error('当前账户还没有孩子档案');state.childId=selected.id;$('#child-name').textContent=selected.name;}
  async function moduleToken(renew=false){if(renew)state.token=null;if(!state.token)await issue();return state.token;}
  async function runtime(path,options={}){return AppRuntimeNetwork.requestJson({url:`${RUNTIME_API}${path}`,options,getToken:moduleToken});}
  function range(){return AppRuntimeTime.beijingRange(state.period,state.offset);}
  function assignmentOptions(selectedId,protectedValue=true){return `<option value="u"${!protectedValue?' selected':''}>成人／不保护</option>`+state.children.map((item,index)=>`<option value="${index}"${protectedValue&&item.id===selectedId?' selected':''}>${escape(item.name)}</option>`).join('');}
  function policyLabel(value){return({pending:'待下发',cached:'已缓存',applied:'当前会话已生效',failed:'失败',offline:'离线'})[value]||'待下发';}
  function statusLabel(value){return({online:'在线',recentlyOnline:'最近在线',offline:'离线',revoked:'已吊销'})[value]||value;}

  function mockData(){const dayStart=AppRuntimeTime.beijingRange('day').from;state.children=[{id:'demo-a',name:'小明'},{id:'demo-b',name:'小华'}];state.childId='demo-a';state.machines=[{id:'machine-a',displayName:'书房电脑',status:'online',defaultChildId:'demo-a',serviceVersion:'2.0.0',windowsVersion:'Windows 11',architecture:'x64',lastSeenAtMs:Date.now()-120000,desiredPolicyVersion:4,appliedPolicyVersion:4,policyState:'applied',tamperCount:1}];state.users.set('machine-a',[{localUserId:'opaque-a',displayName:'William',childId:'demo-a',protected:true,assignmentSource:'default',policyState:'applied',sessionActive:true},{localUserId:'opaque-b',displayName:'Guest',childId:null,protected:false,assignmentSource:'unprotected',policyState:'cached',sessionActive:false}]);return{totalDurationMs:9720000,lastSyncAtMs:Date.now()-180000,buckets:Array.from({length:24},(_,i)=>({startAtMs:dayStart+i*3600000,durationMs:[0,0,0,0,0,0,0,0,900000,1800000,1200000,600000,300000,1500000,2100000,720000,0,600000,0,0,0,0,0,0][i]})),applications:[{displayName:'Visual Studio Code',durationMs:4320000},{displayName:'Microsoft Edge',durationMs:2880000},{displayName:'微信',durationMs:1620000}]};}

  function renderMachines(){const box=$('#machines');box.innerHTML=state.machines.length?state.machines.map(machine=>{const users=state.users.get(machine.id)||[];return `<article class="machine-card"><div class="machine-head"><div><strong>${escape(machine.displayName||'Windows 电脑')}</strong><p>${escape(machine.windowsVersion||'等待首次连接')} · ${escape(machine.architecture||'x64')} · Service ${escape(machine.serviceVersion||'—')}</p><p>最近在线 ${time(machine.lastSeenAtMs)} · 策略 ${machine.appliedPolicyVersion||0}/${machine.desiredPolicyVersion||0}</p></div><span class="badge ${escape(machine.status)}">${statusLabel(machine.status)}</span></div><div class="assignment default-assignment"><label>新用户默认关联<select data-default="${escape(machine.id)}">${state.children.map((item,index)=>`<option value="${index}"${item.id===machine.defaultChildId?' selected':''}>${escape(item.name)}</option>`).join('')}</select></label><span class="policy ${escape(machine.policyState)}">${policyLabel(machine.policyState)}</span></div><div class="user-list">${users.length?users.map(user=>`<div class="user-row"><div><strong>${escape(user.displayName)}</strong><small>${user.sessionActive?'当前会话活动':'当前未登录'}</small></div><select aria-label="${escape(user.displayName)} 的关联" data-machine="${escape(machine.id)}" data-user="${escape(user.localUserId)}">${assignmentOptions(user.childId,user.protected)}</select><span class="policy ${escape(user.policyState)}">${policyLabel(user.policyState)}</span></div>`).join(''):'<p class="empty-copy">Service 首次上报后显示本机用户。</p>'}</div><div class="actions"><button data-uninstall="${escape(machine.id)}">生成卸载码</button>${machine.status!=='revoked'?`<button class="danger" data-revoke="${escape(machine.id)}">吊销机器</button>`:''}</div>${machine.tamperCount?`<p class="tamper">已自动恢复 ${machine.tamperCount} 次 Agent 异常终止</p>`:''}</article>`;}).join(''):'尚未添加 Runtime 电脑';renderFilters();}

  function renderFilters(){const machine=$('#machine-filter');const selected=machine.value;machine.innerHTML='<option value="">全部电脑</option>'+state.machines.filter(item=>item.status!=='revoked').map(item=>`<option value="${escape(item.id)}">${escape(item.displayName||'Windows 电脑')}</option>`).join('');machine.value=selected;const users=$('#user-filter');const userSelected=users.value;const source=selected?state.users.get(selected)||[]:[...state.users.values()].flat();const unique=new Map(source.map(item=>[item.localUserId,item]));users.innerHTML='<option value="">全部本机用户</option>'+[...unique.values()].map(item=>`<option value="${escape(item.localUserId)}">${escape(item.displayName)}</option>`).join('');users.value=userSelected;}
  function renderUsage(u){$('#total-time').textContent=duration(u.totalDurationMs||0);$('#last-sync').textContent=time(u.lastSyncAtMs);const buckets=u.buckets||[];const max=Math.max(1,...buckets.map(b=>b.durationMs));$('#usage-chart').innerHTML=buckets.map(b=>`<div class="bar" title="${duration(b.durationMs)}" style="height:${Math.max(2,b.durationMs/max*100)}%"><span>${state.period==='day'?AppRuntimeTime.beijingHourLabel(b.startAtMs):new Date(b.startAtMs).toLocaleDateString('zh-CN',{weekday:'short',timeZone:'Asia/Shanghai'})}</span></div>`).join('');const apps=u.applications||[];$('#app-ranking').className='list';$('#app-ranking').innerHTML=apps.length?apps.map((a,i)=>`<div class="app-row"><span class="app-icon">${i+1}</span><strong>${escape(a.displayName||'未知应用')}</strong><time>${duration(a.durationMs)}</time></div>`).join(''):'暂无使用记录';}

  async function load({freshToken=false}={}){try{if(freshToken)state.token=null;$('#status-strip').hidden=true;const r=range();$('#range-label').textContent=r.label;$('#chart-caption').textContent=`北京时间，${state.period==='day'?'按小时':'按每日'}`;if(mock){const usage=mockData();$('#child-name').textContent='小明（演示）';renderMachines();renderUsage(usage);return;}await moduleToken(freshToken);const result=await runtime('/v2/module/machines');state.machines=result.machines||[];state.users.clear();await Promise.all(state.machines.map(async machine=>{const result=await runtime(`/v2/module/machines/${encodeURIComponent(machine.id)}/users`);state.users.set(machine.id,result.users||[]);}));renderMachines();const machineId=$('#machine-filter').value;const userId=$('#user-filter').value;const usage=await runtime(`/v2/module/usage?childId=${encodeURIComponent(state.childId)}&fromMs=${r.from}&toMs=${r.to}${machineId?`&machineId=${encodeURIComponent(machineId)}`:''}${userId?`&userId=${encodeURIComponent(userId)}`:''}`);renderUsage(usage);}catch(error){$('#status-strip').hidden=false;$('#status-strip').textContent=AppRuntimeNetwork.friendlyError(error).message;}}

  function openPair(){const select=$('#pair-default-child');select.innerHTML=state.children.map((item,index)=>`<option value="${index}"${item.id===state.childId?' selected':''}>${escape(item.name)}</option>`).join('');$('#pair-result').hidden=true;$('#pair-dialog').showModal();}
  async function createPairing(){const selected=childFromKey($('#pair-default-child').value);if(!selected)throw new Error('请选择默认孩子');const result=mock?{code:'ABCD-EFGH-JKLM',expiresAtMs:Date.now()+600000}:await runtime('/v2/module/pairing-codes',{method:'POST',body:JSON.stringify({defaultChildId:selected.id,displayName:'Windows 电脑'})});showCode('pair',result.code,result.expiresAtMs);$('#pair-result').hidden=false;runtime('/v1/releases/windows/x64/latest').then(release=>{$('#download-installer').href=`${RUNTIME_API}/v1/releases/windows/x64/${encodeURIComponent(release.version)}/installer`;}).catch(()=>{$('#download-installer').removeAttribute('href');$('#download-installer').textContent='安装器准备中';});}
  function copyElements(kind){return kind==='pair'?{button:$('#copy-code'),status:$('#pair-copy-status'),code:$('#pair-code')}:{button:$('#copy-uninstall'),status:$('#uninstall-copy-status'),code:$('#uninstall-code')};}
  function resetCopyFeedback(kind){const elements=copyElements(kind);elements.button.textContent=kind==='pair'?'复制配对码':'复制卸载码';elements.status.hidden=true;elements.status.className='copy-status';elements.status.textContent='';}
  async function copyCode(kind){const elements=copyElements(kind);try{await AppRuntimeClipboard.copyText(elements.code.textContent);elements.button.textContent='已复制';elements.status.className='copy-status';elements.status.textContent='已复制到剪贴板';elements.status.hidden=false;}catch(error){elements.button.textContent='请手动复制';elements.status.className='copy-status error';elements.status.textContent=error?.message||'复制失败，请手动选择代码。';elements.status.hidden=false;}}
  function showCode(kind,code,expires){const codeBox=kind==='pair'?$('#pair-code'):$('#uninstall-code');const countdown=kind==='pair'?$('#pair-countdown'):$('#uninstall-countdown');resetCopyFeedback(kind);codeBox.textContent=code;clearInterval(state.timer);const tick=()=>{const seconds=Math.max(0,Math.ceil((expires-Date.now())/1000));countdown.textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')} 后过期`;};tick();state.timer=setInterval(tick,1000);}

  document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;try{if(button.id==='add-machine')openPair();if(button.id==='create-pairing')await createPairing();if(button.id==='copy-code')await copyCode('pair');if(button.id==='copy-uninstall')await copyCode('uninstall');if(button.dataset.uninstall){const result=mock?{code:'UNIN-STALL-CODE',expiresAtMs:Date.now()+600000}:await runtime(`/v2/module/machines/${encodeURIComponent(button.dataset.uninstall)}/uninstall-codes`,{method:'POST',body:'{}'});showCode('uninstall',result.code,result.expiresAtMs);$('#uninstall-dialog').showModal();}if(button.dataset.revoke&&!mock&&confirm('吊销后，这台电脑将停止采集和上传。确定继续？')){await runtime(`/v2/module/machines/${encodeURIComponent(button.dataset.revoke)}/revoke`,{method:'POST',body:'{}'});await load();}if(button.dataset.period){state.period=button.dataset.period;state.offset=0;document.querySelectorAll('[data-period]').forEach(item=>item.classList.toggle('active',item===button));await load();}if(button.id==='previous'){state.offset--;await load();}if(button.id==='today'){state.offset=0;await load();}if(button.id==='refresh')await load({freshToken:true});}catch(error){$('#status-strip').hidden=false;$('#status-strip').textContent=AppRuntimeNetwork.friendlyError(error).message;}});
  document.addEventListener('change',async event=>{const select=event.target.closest('select');if(!select)return;try{if(select.dataset.default){const selected=childFromKey(select.value);if(selected&&!mock){await runtime(`/v2/module/machines/${encodeURIComponent(select.dataset.default)}/default-assignment`,{method:'PATCH',body:JSON.stringify({childId:selected.id})});await load();}}else if(select.dataset.user){const selected=select.value==='u'?null:childFromKey(select.value);if(!mock){await runtime(`/v2/module/machines/${encodeURIComponent(select.dataset.machine)}/users/${encodeURIComponent(select.dataset.user)}`,{method:'PATCH',body:JSON.stringify({protected:Boolean(selected),childId:selected?.id||null})});await load();}}else if(select.id==='machine-filter'){renderFilters();await load();}else if(select.id==='user-filter')await load();}catch(error){$('#status-strip').hidden=false;$('#status-strip').textContent=AppRuntimeNetwork.friendlyError(error).message;}});
  load();
})();
