const assert=require('node:assert/strict');
const K=require('./app-runtime-knowledge');
const evidence={platform:'windows',runtimeIdentity:'fixture',displayName:'Fixture game',values:{binaryHash:'a'.repeat(64),signerKey:'b'.repeat(64),productName:'Fixture game'},verifiedFields:['binaryHash','signerKey']};
const confirmed=K.confirmProduct(K.empty(),{evidence,scope:'file',name:'Fixture game',type:'game',classification:'restrictedEntertainment',childIds:['child-a'],id:'fixture-game'});
assert.deepEqual(confirmed.bindings.map(item=>item.childId),['child-a']);
assert.equal(confirmed.products[0].selectors[0].match.conditions[0].field,'binaryHash');
assert.throws(()=>K.selectorFor({...evidence,verifiedFields:[]},'series'),/可靠身份/);
assert.deepEqual(K.selectorFor(evidence,'series').match.conditions.map(item=>item.field),['signerKey','productName']);
const variant=K.confirmProduct(confirmed,{evidence:{...evidence,values:{...evidence.values,binaryHash:'c'.repeat(64)}},scope:'file',productId:'fixture-game',classification:'restrictedEntertainment',childIds:['child-a']});
assert.equal(variant.products[0].selectors.length,2);
assert.equal(K.unlinkVariant(variant,'fixture-game',1,['child-a']).products[0].selectors.length,1);
assert.throws(()=>K.unlinkVariant(confirmed,'fixture-game',0,[]),/其他孩子/);
assert.equal(K.unlinkVariant(confirmed,'fixture-game',0,['child-a']).products.length,0);
assert.equal(K.unlinkVariant(confirmed,'fixture-game',0,['child-a']).bindings[0].products.length,0);
const split=K.splitVariant(variant,'fixture-game',1,{id:'split-game',name:'Different game',childId:'child-a',classification:'blocked'});
assert.equal(split.products.length,2);assert.equal(split.products[0].selectors.length,1);
assert.throws(()=>K.mergeProducts(split,'split-game','fixture-game','child-a'),/分类冲突/);
split.bindings[0].products[1].classification='restrictedEntertainment';
assert.equal(K.mergeProducts(split,'split-game','fixture-game','child-a').products.length,1);
split.bindings.push({childId:'child-b',products:[{productId:'split-game',classification:'study'}],ruleIds:[]});
assert.throws(()=>K.mergeProducts(split,'split-game','fixture-game','child-a'),/其他孩子/);
const incoming={schemaVersion:1,version:0,products:[{id:'name-only',name:'Unknown game',type:'game',selectors:[]}],rules:[],bindings:[{childId:'child-a',products:[{productId:'name-only',classification:'blocked'}],ruleIds:[]}]};
const preview=K.diffImport(confirmed,incoming);
assert.deepEqual(preview.warnings,['Unknown game']);assert.equal(preview.incoming.rules[0].mode,'suggestion');
assert.throws(()=>K.selectedImport(confirmed,preview.incoming,[]),/逐项/);
const selected=K.selectedImport(confirmed,preview.incoming,preview.changes.map(item=>item.key));
assert.deepEqual(selected.bindings[0].products,confirmed.bindings[0].products);
assert.equal(selected.rules.length,1);assert.equal(confirmed.rules.length,0);
assert.deepEqual(K.scopeImport({...incoming,bindings:[{childId:'injected-child',products:[],ruleIds:[]}]},['child-a']).bindings.map(item=>item.childId),['child-a']);
const shared={...K.empty(),rules:[{id:'old-rule',enabled:true,name:'Old'}],bindings:[{childId:'child-a',products:[],ruleIds:['old-rule']},{childId:'child-b',products:[],ruleIds:['old-rule']}]};
const revised=K.reviseRule(shared,{id:'new-rule',enabled:true,name:'Revised'},['child-a'],'old-rule');
assert.deepEqual(revised.bindings[0].ruleIds,['new-rule']);assert.deepEqual(revised.bindings[1].ruleIds,['old-rule']);
assert.deepEqual(K.toggleApproval(shared,'old-rule','child-a','unused').bindings[1].ruleIds,['old-rule']);
assert.deepEqual(K.toggleApproval(shared,'old-rule','child-a','unused').bindings[0].ruleIds,[]);
assert.throws(()=>K.selectedImport(shared,{products:[],rules:[{id:'old-rule',enabled:true,name:'Changed'}],bindings:[{childId:'child-a',products:[],ruleIds:['old-rule']}]},['rules:old-rule']),/未选孩子/);
const oldMatch={match:{conditions:[{field:'packageId',value:'not-currently-installed'},{field:'binaryHash',value:'a'.repeat(64)},{field:'productName',value:'Old name'},{field:'declaredType',value:'game'}]}};
assert.deepEqual(K.editedConditions(oldMatch,[{field:'binaryHash',value:'a'.repeat(64)}],[],'New name'),[{field:'packageId',value:'not-currently-installed'},{field:'declaredType',value:'game'},{field:'productName',value:'New name'}]);
assert.deepEqual(K.editedConditions(null,[],[{field:'binaryHash',value:'x'},{field:'binaryHash',value:'x'}],''),[{field:'binaryHash',value:'x'}]);
const hitHTML=K.previewHitsHTML([{childIndex:0,displayName:'<video>',platform:'windows',result:{classification:'study',status:'conflict',productId:'private-product',ruleIds:['private-rule']}}],[{id:'private-child',name:'测试孩子'}]);
assert.match(hitHTML,/规则冲突，保留原有效分类/);assert.match(hitHTML,/&lt;video&gt;/);assert.match(hitHTML,/测试孩子/);assert(!hitHTML.includes('private-'));
console.log('PASS: knowledge UI scope, variants, merge guards and selected import');
