const assert = require('node:assert/strict');
const policy = require('./app-runtime-policy.js');

const base = policy.defaultPolicy();
assert.equal(base.quotas.dailyCategoryMinutes.study, null);
assert.deepEqual(base.timeWindows.monday.study, [{ start: '00:00', end: '24:00' }]);
const classified = policy.classify(base, { platform: 'windows', runtimeIdentity: 'app:a', displayName: 'A' }, 'study');
assert.equal(classified.classifications[0].classification, 'study');
const replaced = policy.classify(classified, { platform: 'windows', runtimeIdentity: 'app:a', displayName: 'A2' }, 'blocked');
assert.equal(replaced.classifications.length, 1);
assert.equal(replaced.classifications[0].classification, 'blocked');
const other = policy.classify(replaced, { platform: 'windows', runtimeIdentity: 'app:a', displayName: 'A2' }, 'other');
assert.equal(other.classifications[0].classification, 'other');
assert.equal(policy.scheduleCategories.includes('other'), false, 'other has no common time window');
const diff = policy.importDiff(base, policy.exportPayload(replaced));
assert.deepEqual({ added: diff.added, changed: diff.changed, removed: diff.removed }, { added: 1, changed: 0, removed: 0 });
assert.equal(policy.exportPayload(replaced).schemaVersion, 3);
assert.deepEqual(policy.exportPayload(replaced).quotas, { perApplicationDailyMinutes: [] });
assert.equal(Object.hasOwn(policy.exportPayload(replaced), 'timeWindows'), false,
  'app export does not create a second child-level public schedule');
const appOnly = policy.defaultPolicy();
appOnly.quotas.dailyCategoryMinutes.study = 90;
appOnly.timeWindows.monday.study = [];
const appOnlyImport = policy.importDiff(appOnly, { schemaVersion: 3, classifications: [], quotas: { perApplicationDailyMinutes: [] } });
assert.equal(appOnlyImport.quotasChanged, false, 'app-only import does not reset common quotas');
assert.equal(appOnlyImport.timeWindowsChanged, false, 'app-only import does not reset common time windows');
assert.equal(appOnlyImport.policy.quotas.dailyCategoryMinutes.study, 90);
assert.deepEqual(appOnlyImport.policy.timeWindows.monday.study, []);
const v1 = policy.importDiff(base, { schemaVersion: 1, classifications: [], quotas: base.quotas });
assert.deepEqual(v1.policy.timeWindows, policy.allOpenTimeWindows());
const closed = policy.allOpenTimeWindows();
closed.monday.study = [];
const scheduleDiff = policy.importDiff(base, { schemaVersion: 2, classifications: [], quotas: base.quotas, timeWindows: closed });
assert.equal(scheduleDiff.timeWindowsChanged, true);
assert.deepEqual(scheduleDiff.policy.timeWindows.monday.study, []);
const legacySharedDiff = policy.importDiff(base, { schemaVersion: 2, classifications: [],
  quotas: { ...base.quotas, dailyCategoryMinutes: { ...base.quotas.dailyCategoryMinutes, study: 25 } }, timeWindows: closed });
assert.equal(legacySharedDiff.quotasChanged, false, 'legacy common quotas are not counted as app-only changes');
assert.throws(() => policy.normalize({ timeWindows: { monday: {} } }), /缺少/);
assert.throws(() => policy.importDiff(base, { schemaVersion: 4 }), /不支持/);
console.log('app-runtime-policy tests passed');
