const assert = require('node:assert/strict');
const policy = require('./app-runtime-policy.js');

const base = policy.defaultPolicy();
assert.equal(base.quotas.dailyCategoryMinutes.study, null);
assert.deepEqual(base.timeWindows.monday.study, [{ start: '00:00', end: '24:00' }]);
const classified = policy.classify(base, { platform: 'windows', runtimeIdentity: 'app:a', displayName: 'A' }, 'study');
assert.equal(classified.classifications[0].classification, 'study');
const replaced = policy.classify(classified, { platform: 'windows', runtimeIdentity: 'app:a', displayName: 'A2' }, 'blocked');
assert.equal(replaced.classifications.length, 1);
assert.equal(replaced.classifications[0].classification, 'blocked');
const diff = policy.importDiff(base, policy.exportPayload(replaced));
assert.deepEqual({ added: diff.added, changed: diff.changed, removed: diff.removed }, { added: 1, changed: 0, removed: 0 });
assert.equal(policy.exportPayload(replaced).schemaVersion, 2);
const v1 = policy.importDiff(base, { schemaVersion: 1, classifications: [], quotas: base.quotas });
assert.deepEqual(v1.policy.timeWindows, policy.allOpenTimeWindows());
const closed = policy.allOpenTimeWindows();
closed.monday.study = [];
const scheduleDiff = policy.importDiff(base, { schemaVersion: 2, classifications: [], quotas: base.quotas, timeWindows: closed });
assert.equal(scheduleDiff.timeWindowsChanged, true);
assert.deepEqual(scheduleDiff.policy.timeWindows.monday.study, []);
assert.throws(() => policy.normalize({ timeWindows: { monday: {} } }), /缺少/);
assert.throws(() => policy.importDiff(base, { schemaVersion: 3 }), /不支持/);
console.log('app-runtime-policy tests passed');
