const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const view=require('./computer-usage-view.js');
const raw=fs.readFileSync(path.join(__dirname,'computer-usage-view.js'),'utf8');
const controller=fs.readFileSync(path.join(__dirname,'app-runtime.js'),'utf8');
assert.ok(controller.includes('特殊应用 · 原应用配置：'));
assert.ok(controller.includes("current==='special'?'特殊应用':'普通应用'"));
const directory=controller.match(/function directoryMembers\(category\) \{([\s\S]*?)\n  \}/)[0];
const state={catalog:{items:[{platform:'windows',runtimeIdentity:null,presentationKind:'contentBased',runtimeImplementations:[{platform:'windows',runtimeIdentity:'chrome1'},{platform:'windows',runtimeIdentity:'chrome2'}]}]},records:{pending:[{platform:'windows',runtimeIdentity:'chrome1'},{platform:'windows',runtimeIdentity:'chrome2'},{platform:'windows',runtimeIdentity:'excel'}]}};
const keyOf=item=>item.platform+'|'+item.runtimeIdentity;
const members=new Function('state','AppRuntimePolicy','$',directory+';return directoryMembers;')(state,{keyOf},()=>({value:'usage'}));
assert.equal(members('special').length,1);assert.deepEqual(members('unclassified').map(item=>item.runtimeIdentity),['excel']);
assert.equal(raw,fs.readFileSync(path.join(__dirname,'../../pages/computer-usage-view.js'),'utf8'),'both cloud pages use identical readonly renderer');
const snapshot={schemaVersion:1,revision:'r1',fromDate:'2026-10-01',toDate:'2026-10-01',complete:false,reasons:['DEVICE_MAPPING_INCOMPLETE'],totals:{computerMs:null,webMs:1501,applicationMs:3001,overlapMs:null},categoriesMs:{study:null},devices:[{key:'opaque',name:'电脑',complete:false,totalMs:null,webMs:1501,applicationMs:3001,chromeUnexplainedMs:null}],sourceVersions:[{kind:'web',settledAtMs:null}]};
const html=view.summary(snapshot);assert.ok(html.includes('网页设备与电脑之间缺少可信关联'));assert.ok(html.includes('1秒 501毫秒'));assert.ok(html.includes('不可用'));assert.ok(!html.includes('usage-stack-chart'));
assert.equal(view.duration(null),'不可用');assert.equal(view.duration(0),'0分 0秒');assert.equal(view.duration(1501),'0分 1秒 501毫秒');
const products=view.detailRows('products',[{key:'opaque-product',name:'<script>x</script>',source:'application',special:true,durationMs:1501,classification:['study'],chromeContent:{complete:false,explainedMs:null,unexplainedMs:null,categoriesMs:{study:null}}}]);
assert.ok(products.includes('&lt;script&gt;'));assert.ok(!products.includes('<script>'));assert.ok(products.includes('data-computer-chrome="opaque-product"'));assert.ok(products.includes('网页统计有缺失'));
assert.ok(products.includes('原应用历史归类，仅用于原口径；不贡献统一分类'));
const childContent=view.detailRows('products',[{key:'child-chrome',name:'Chrome',source:'application',special:true,durationMs:1501,classification:['composite'],chromeContent:{scope:'child',webMs:3000,complete:true,explainedMs:null,unexplainedMs:null,categoriesMs:{study:3000}}}]);
assert.ok(childContent.includes('该孩子的网页内容'));assert.ok(childContent.includes('不代表容器内访问，不扣除重叠'));assert.ok(!childContent.includes('网页解释'));
const statusHtml=view.summary({...snapshot,sourceStatus:{web:'complete',application:'partial'},historyStatus:'bestEffort',overlapStatus:'unconfirmed',categoryBasis:'sourceCumulative',categoriesMs:{study:1501},sourceCategoriesMs:{web:{study:1501},application:{composite:3001}}});
assert.ok(statusHtml.includes('来源累计、尚未去重'));assert.ok(statusHtml.includes('不是完整合计'));assert.ok(statusHtml.includes('独立权威分类'));assert.ok(statusHtml.includes('包含旧版历史'));
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
const pending=deferred(),events={},host={innerHTML:'',classList:{add(){}},addEventListener(name,fn){events[name]=fn;},querySelector(){return null;}};
const reader=view.create(host,()=>pending.promise);const work=reader.load();reader.invalidate();pending.resolve(snapshot);
work.then(()=>{assert.ok(!host.innerHTML.includes('电脑总用量'),'late invalidated response cannot paint');console.log('PASS computer usage renderer: precision, unknown≠zero, safe labels, Chrome expand, shared views, stale responses');}).catch(error=>{console.error(error);process.exitCode=1;});
