import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolveApplication, safeAutomatic } from './dist/application-classification.js';
import { parseApplicationKnowledge, parseAppEvidence } from './dist/application-knowledge-validation.js';
const vectors = JSON.parse(readFileSync(new URL('./application-classification.vectors.json', import.meta.url)));
for (const vector of vectors.cases) assert.deepEqual(resolveApplication(vector.knowledge, vector.childId, vector.evidence, vector.previous), vector.expected, vector.name);
assert.equal(safeAutomatic({operator:'any',conditions:[]}),false);
assert.equal(safeAutomatic({operator:'invalid',conditions:[{field:'binaryHash',value:'hash'}]}),false);
const valid = {schemaVersion:1,version:0,products:[],rules:[],bindings:[]};
assert.deepEqual(parseApplicationKnowledge(valid), valid);
assert.notEqual(parseApplicationKnowledge(valid), valid);
assert.throws(() => parseApplicationKnowledge({...valid,path:'C:/private'}), /INVALID_APPLICATION_KNOWLEDGE/);
assert.throws(() => parseApplicationKnowledge({...valid,products:[{id:'p',name:'Game',type:'game',selectors:[{platform:'windows',match:{operator:'all',conditions:[{field:'productName',value:'Game'}]}}]}]}), /WEAK_PRODUCT_SELECTOR/);
const rule = {id:'r',name:'Rule',kind:'developer',match:{operator:'all',conditions:[{field:'productName',value:'Game'}]},exclude:[],mode:'automatic',classification:'restrictedEntertainment',type:'game',enabled:true,source:'fixture',reason:'fixture'};
assert.throws(() => parseApplicationKnowledge({...valid,rules:[rule]}), /WEAK_AUTOMATIC_RULE/);
assert.throws(() => parseApplicationKnowledge({...valid,rules:[{...rule,kind:'product',match:{operator:'all',conditions:[{field:'signerKey',value:'signer'}]}}]}), /INVALID_PRODUCT_RULE_SCOPE/);
assert.throws(() => parseApplicationKnowledge({...valid,bindings:[{childId:'child',products:[],ruleIds:['missing']}]}), /INVALID_CHILD_BINDING/);
const evidence = {platform:'windows',runtimeIdentity:'opaque',displayName:'App',values:{},verifiedFields:['runtimeIdentity']};
assert.deepEqual(parseAppEvidence(evidence),evidence);
assert.throws(() => parseAppEvidence({...evidence,productId:'forged'}), /INVALID_APPLICATION_EVIDENCE/);
assert.throws(() => parseAppEvidence({...evidence,values:{path:'C:/private'}}), /INVALID_APPLICATION_EVIDENCE/);
assert.throws(() => parseAppEvidence({...evidence,verifiedFields:['signerKey']}), /MISSING_VERIFIED_VALUE/);
assert.throws(() => parseAppEvidence({...evidence,values:{signerKey:'certificate-plaintext'}}), /INVALID_OPAQUE_APPLICATION_EVIDENCE/);
assert.throws(() => parseAppEvidence({...evidence,values:{productName:'C:/Users/private/game.exe'}}), /PRIVATE_APPLICATION_EVIDENCE/);
assert.throws(() => parseApplicationKnowledge({...valid,products:[{id:'p',name:'Game',type:'game',selectors:[{platform:'windows',match:{operator:'all',conditions:[{field:'signerKey',value:'signer'}]}}]}]}), /BROAD_PRODUCT_SELECTOR/);
const schema = JSON.parse(readFileSync(new URL('./application-knowledge.schema.json', import.meta.url)));
assert.equal(schema.additionalProperties,false);
assert.deepEqual(schema.required,Object.keys(valid));
console.log('classification vectors: '+vectors.cases.length+' PASS');
