import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolveApplication, safeAutomatic, associateApplicationEvidence } from './dist/application-classification.js';
import { parseApplicationKnowledge, parseAppEvidence } from './dist/application-knowledge-validation.js';
const vectors = JSON.parse(readFileSync(new URL('./application-classification.vectors.json', import.meta.url)));
const legacyShape = result => ({productId:result.productId,classification:result.classification,status:result.status,ruleIds:result.ruleIds,suggestions:result.suggestions});
for (const vector of vectors.cases) assert.deepEqual(legacyShape(resolveApplication(vector.knowledge, vector.childId, vector.evidence, vector.previous)), vector.expected, vector.name);
assert.equal(safeAutomatic({operator:'any',conditions:[]}),false);
assert.equal(safeAutomatic({operator:'invalid',conditions:[{field:'binaryHash',value:'hash'}]}),false);
const valid = {schemaVersion:1,version:0,products:[],rules:[],bindings:[]};
assert.deepEqual(parseApplicationKnowledge(valid), valid);
assert.notEqual(parseApplicationKnowledge(valid), valid);
assert.throws(() => parseApplicationKnowledge({...valid,path:'C:/private'}), /INVALID_APPLICATION_KNOWLEDGE/);
assert.throws(() => parseApplicationKnowledge({...valid,products:[{id:'p',name:'Game',type:'game',selectors:[{platform:'windows',match:{operator:'all',conditions:[{field:'productName',value:'Game'}]}}]}]}), /WEAK_PRODUCT_SELECTOR/);
const rule = {id:'r',name:'Rule',kind:'developer',match:{operator:'all',conditions:[{field:'productName',value:'Game'}]},exclude:[],mode:'automatic',classification:'restrictedEntertainment',type:'game',enabled:true,source:'fixture',reason:'fixture'};
assert.throws(() => parseApplicationKnowledge({...valid,rules:[rule]}), /WEAK_AUTOMATIC_RULE/);
assert.throws(() => parseApplicationKnowledge({...valid,rules:[{...rule,kind:'product',match:{operator:'all',conditions:[{field:'signerKey',value:'signer'}]}}]}), /INVALID_PRODUCT_RULE_SCOPE/);
assert.throws(() => parseApplicationKnowledge({...valid,bindings:[{childId:'child',products:[],ruleIds:['missing']}]}), /INVALID_CHILD_BINDING/);
const evidence = {platform:'windows',runtimeIdentity:'opaque',displayName:'App',values:{},verifiedFields:['runtimeIdentity']};
assert.deepEqual(parseAppEvidence(evidence),evidence);
const discovery = {role:'component',nameSource:'fallback',sourceKinds:['package']};
assert.deepEqual(parseAppEvidence({...evidence,discovery}).discovery,discovery);
const systemDiscovery = {role:'application',nameSource:'appList',sourceKinds:['package'],applicationOrigin:'operatingSystem',originEvidenceCode:'exactPackageRule'};
assert.deepEqual(parseAppEvidence({...evidence,discovery:systemDiscovery}).discovery,systemDiscovery);
assert.deepEqual(parseAppEvidence({...evidence,discovery:{...discovery,applicationOrigin:'unknown'}}).discovery.applicationOrigin,'unknown');
assert.throws(()=>parseAppEvidence({...evidence,discovery:{...discovery,originEvidenceCode:'exactPackageRule'}}),/INVALID_DISCOVERY_SUMMARY/);
assert.throws(()=>parseAppEvidence({...evidence,discovery:{...discovery,path:'C:/private'}}),/INVALID_DISCOVERY_SUMMARY/);
const packaged = {...evidence,runtimeIdentity:'package-main',values:{packageId:'Fixture!Main'},verifiedFields:['packageId']};
const runtime = {...packaged,runtimeIdentity:'old-binary-id',values:{packageId:'Fixture!Main',binaryHash:'a'.repeat(64)},verifiedFields:['packageId','binaryHash']};
const copy = {...evidence,runtimeIdentity:'copy-id',values:{binaryHash:'a'.repeat(64)},verifiedFields:['binaryHash']};
let associated=associateApplicationEvidence([packaged,runtime,copy,{...evidence,runtimeIdentity:'same-name'}]);
assert.equal(associated.get('windows\npackage-main'),associated.get('windows\nold-binary-id'));
assert.equal(associated.get('windows\ncopy-id'),associated.get('windows\nold-binary-id'));
assert.notEqual(associated.get('windows\nsame-name'),associated.get('windows\nold-binary-id'));
associated=associateApplicationEvidence([runtime,{...runtime,runtimeIdentity:'second-app',values:{...runtime.values,packageId:'Fixture!Video'}}]);
assert.notEqual(associated.get('windows\nold-binary-id'),associated.get('windows\nsecond-app'));
assert.throws(() => parseAppEvidence({...evidence,productId:'forged'}), /INVALID_APPLICATION_EVIDENCE/);
assert.throws(() => parseAppEvidence({...evidence,values:{path:'C:/private'}}), /INVALID_APPLICATION_EVIDENCE/);
assert.throws(() => parseAppEvidence({...evidence,verifiedFields:['signerKey']}), /MISSING_VERIFIED_VALUE/);
assert.throws(() => parseAppEvidence({...evidence,values:{signerKey:'certificate-plaintext'}}), /INVALID_OPAQUE_APPLICATION_EVIDENCE/);
assert.throws(() => parseAppEvidence({...evidence,values:{productName:'C:/Users/private/game.exe'}}), /PRIVATE_APPLICATION_EVIDENCE/);
assert.throws(() => parseApplicationKnowledge({...valid,products:[{id:'p',name:'Game',type:'game',selectors:[{platform:'windows',match:{operator:'all',conditions:[{field:'signerKey',value:'signer'}]}}]}]}), /BROAD_PRODUCT_SELECTOR/);
const typeKnowledge={schemaVersion:2,version:1,products:[{id:'aimlabs',name:'Aimlabs',type:'game',selectors:[{platform:'windows',match:{operator:'all',conditions:[{field:'distributionKey',value:'steam:714010'}]}}]}],rules:[{id:'games',name:'Games',kind:'type',match:{operator:'all',conditions:[]},exclude:[],mode:'automatic',classification:'restrictedEntertainment',type:'game',enabled:true,source:'fixture',reason:'confirmed type'}],bindings:[{childId:'child',products:[],ruleIds:['games']}]};
const aimlabs={platform:'windows',runtimeIdentity:'opaque',displayName:'Aimlabs',values:{distributionKey:'steam:714010'},verifiedFields:['distributionKey']};
assert.deepEqual(resolveApplication(typeKnowledge,'child',aimlabs),{productId:'aimlabs',classification:'restrictedEntertainment',status:'automatic',ruleIds:['games'],suggestions:[],appType:'game',typeStatus:'confirmed',typeReasonCode:'distributionProductRule'});
assert.equal(resolveApplication({...typeKnowledge,bindings:[{childId:'child',products:[{productId:'aimlabs',classification:'composite'}],ruleIds:['games']}]},'child',aimlabs).classification,'composite');
assert.equal(resolveApplication(typeKnowledge,'child',{...aimlabs,runtimeIdentity:'spoof',values:{declaredType:'game'},verifiedFields:[]}).typeStatus,'unknown');
assert.throws(()=>parseAppEvidence({...aimlabs,values:{distributionKey:'unknown:714010'}}),/INVALID_DISTRIBUTION_KEY/);
const schema = JSON.parse(readFileSync(new URL('./application-knowledge.schema.json', import.meta.url)));
assert.equal(schema.additionalProperties,false);
assert.deepEqual(schema.required,Object.keys(valid));
console.log('classification vectors: '+vectors.cases.length+' PASS');
