const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const load = (file, names, deps = {}) => new Function(...Object.keys(deps), fs.readFileSync(path.join(__dirname, '../../', file), 'utf8')
  .replace(/^import .*;\r?\n/gm, '').replace(/export /g, '') + `\nreturn {${names}}`)(...Object.values(deps));
const api = load('extension/core/quota-audit.js', 'validateQuotaAuditRequest,buildQuotaAuditSnapshot,verifyQuotaAuditPackets,compareQuotaAudit,projectAuditSegment,QUOTA_AUDIT_KEYS');
(async () => {
  const now = Date.now(), date = new Date(now + 8 * 3600000).toISOString().slice(0, 10);
  const request = { requestId: 'request-test', deviceId: 'device-test', fromDate: date, toDate: date, expiresAt: now + 86400000 };
  assert(api.validateQuotaAuditRequest(request, now));
  assert(!api.validateQuotaAuditRequest({ ...request, fromDate: '2026-02-30' }, now));
  assert(!api.validateQuotaAuditRequest({ ...request, expiresAt: now + 86400001 }, now));
  const segment = { id: 's1', date, startMs: now - 19009000, endMs: now, durationSeconds: 19009, channel: 'active', mode: 'rest', targetClassificationAtTime: 'pending_composite', quotaBucketAtTime: 'rest', url: 'https://secret.example', token: 'secret' };
  const data = { usage_segments_v1: { s1: segment }, daily_usage_stats_v1: { [date]: { targets: { private: { activeByQuotaBucket: { rest: 19009 } } } } }, segment_sync_outbox_v1: { dirtySegmentIds: ['s1', ...Array.from({ length: 693 }, (_, i) => `pending-${i}`)] } };
  const packets = await api.buildQuotaAuditSnapshot(data, request, now, 'snapshot-test');
  assert(!JSON.stringify(packets).includes('secret'));
  assert(!JSON.stringify(packets).includes('private'));
  const verified = await api.verifyQuotaAuditPackets(packets);
  assert.equal(verified.complete, true);
  const diff = api.compareQuotaAudit(verified, []);
  assert.equal(diff.days[0].localRawRest - diff.days[0].cloudRawRest, 19009);
  assert.equal(diff.pendingIds.length, 694);
  assert.equal(diff.days[0].aggregateDelta, 0);
  assert.equal((await api.verifyQuotaAuditPackets(packets.filter((_, i) => i !== 1))).complete, false);
  const corrupt = structuredClone(packets); corrupt[1].rows[0][5]++;
  assert.equal((await api.verifyQuotaAuditPackets(corrupt)).reason, 'checksum_mismatch');
  assert.equal(api.compareQuotaAudit(verified, [api.projectAuditSegment({ ...segment, durationSeconds: 1 })]).conflicts.length, 1);
  const zero = await api.buildQuotaAuditSnapshot({ usage_segments_v1: { zero: { ...segment, id: 'zero', startMs: now, endMs: now, durationSeconds: 0 } } }, request, now, 'snapshot-zero');
  const zeroReport = api.compareQuotaAudit(await api.verifyQuotaAuditPackets(zero), []);
  assert.equal(zeroReport.validationCandidates[0].reasons[0], 'non_positive_range');
  assert.equal(zeroReport.days[0].aggregateDelta, null);
  const storage = area => ({ get: async keys => Object.fromEntries((Array.isArray(keys) ? keys : [keys]).map(k => [k, structuredClone(area[k])])), remove: async k => { delete area[k]; } });
  const local = { ...data, guardian_config: { clientLoggingPolicyV1: { uploadEnabled: true, quotaAuditRequest: request } }, cloud_device_id: 'device-test' }, session = {};
  global.chrome = { storage: { local: storage(local), session: storage(session) }, runtime: { getManifest: () => ({ version: 'test' }) } };
  const runner = load('extension/infra/quota-audit-upload.js', 'pumpQuotaAudit', { ...api, budgetedLocalSet: async values => { Object.assign(local, structuredClone(values)); return { ok: true }; }, budgetedSessionSet: async values => { Object.assign(session, structuredClone(values)); return { ok: true }; } });
  const sent = [];
  const upload = async (_, options) => { const logs = JSON.parse(options.body).logs; sent.push(...logs); return { acceptedIds: logs.map(l => l.id) }; };
  let result;
  for (let i = 0; i < 10; i++) { result = await runner.pumpQuotaAudit(upload, now); if (result.complete) break; }
  assert.equal(result.complete, true);
  assert.equal((await api.verifyQuotaAuditPackets(sent.map(l => l.details))).complete, true);
  const before = sent.length; await runner.pumpQuotaAudit(upload, now); assert.equal(sent.length, before);
  local.guardian_config.clientLoggingPolicyV1.quotaAuditRequest = { ...request, requestId: 'request-2' };
  const missing = await runner.pumpQuotaAudit(async () => ({ acceptedIds: [] }), now);
  assert.equal(missing.missingAck, true);
  delete session.quota_audit_buffer_v1;
  await runner.pumpQuotaAudit(upload, now);
  assert.equal(sent.at(-1).details.reason, 'audit_buffer_lost');
  local.guardian_config.clientLoggingPolicyV1.uploadEnabled = false;
  assert.equal((await runner.pumpQuotaAudit(upload, now)).skipped, 'not_authorized');
  console.log('PASS quota audit: 19009s/694 IDs, checksum, missing packets, privacy, ACK, restart and consent');
})().catch(e => { console.error(e); process.exitCode = 1; });
